apiVersion: image.openshift.io/v1
kind: "ImageStream"
metadata:
  name: "openvino-toolkit"
  labels:
    application: s2i-openvino-notebook
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with OpenVINO Toolkit
      and dependencies to start experimenting with advanced AI/ML notebooks.
    opendatahub.io/notebook-image-name: OpenVINO Toolkit
    opendatahub.io/notebook-image-url: 'https://github.com/openvinotoolkit/openvino'
spec:
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: "{{ .Values.image_name }}"
      importPolicy: { }
      referencePolicy:
        type: Source